spring:
  application:
    name: Authorization API
    version: 1.0.0
    description: Aplicativo/API Authorization
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
#        ddl-auto: create
        ddl-auto: update
    properties:
        hibernate:
            temp:
               use_jdbc_metadata_defaults: false
server:
  port: ${SERVER_PORT:8089}
  servlet:
     context-path: /authorization
